package org.example;

public enum TokenType {
    IF, THEN, ELSE, ELSEIF, END, OUTPUT,
    IDENTIFIER, CONSTANT,
    COMPARISON_OPERATOR, UNARY_LOGICAL_OPERATION, BINARY_LOGICAL_OPERATION, ARITHMETIC_OPERATION,
    UNKNOWN
}
